p1 = float(input('Digite o primeiro produto:  '))
p2 = float(input('Digite o segundo produto:  '))
p3 = float(input('Digite o terceiro produto:  '))
p4 = float(input('Digite o quarto produto:  '))
p5 = float(input('Digite o quinto produto:  '))
d = float(input ('Digite a quantidade de Reais:  '))
t = d - (p1 + p2 + p3 + p4 + p5) 
print ('Seu troco é:  ', t)
